### ISSUE TITLE
Failed building wheel for diff_gaussian_rasterization and simple_knn

### ISSUE THREAD

**Issue by subrotoxing** [haoyuhsu/autovfx#3]
error in pip install submodules/diff-gaussian-rasterization

`fatal error C1083: Cannot open include file: 'cuda/std/type_traits': No such file or directory
`

and  pip install submodules/simple-knn

` simple_knn.cu(17): fatal error C1083: Cannot open include file: 'cub/cub.cuh': No such file or directory
      simple_knn.cu`

please advise thanks.

**Comment by ysxk** [comment]
The same problem, I am looking for a solution and don't know which version of Visual Studio to download. Even if I install the latest version, this error will still occur

**Comment by ysxk** [comment]
Installing Visual Studio 2019 can solve this problem by simply selecting C++desktop development
VS2019 is no longer available on the official website, you can download it through my cloud drive
You can also search for him on search engines
There may be some files that need to be solved. Indeed, this can be quickly found on the Internet

https://www.123684.com/s/nApcVv-lFZ4H

![db2f39f7f3705bee905a383ee8fb39f](https://github.com/user-attachments/assets/3eb9c657-d639-49b3-8bbd-876ef155c4ea)

**Comment by haoyuhsu** [comment]
Hi,

I have only tested this on Linux OS, so I am not familiar with installation issues on Windows. However, for problems related to `diff-gaussian-rasterization` and `simple-knn`, I recommend referring to the original [Gaussian Splatting](https://github.com/graphdeco-inria/gaussian-splatting), as I built upon that repository. You can also check out issues like [this one](https://github.com/graphdeco-inria/gaussian-splatting/issues/237) for more detailed discussions about building the wheel on Windows.

Hope this would help!
