### ISSUE TITLE
Reproducibility Issue with BakedSDF Garden Data

### ISSUE THREAD

**Issue by seongyeong2** [haoyuhsu/autovfx#4]
Hello,
Thank you for your excellent research.

I have trained BakedSDF with the following configuration in sdfstudio:

`ns-train bakedsdf-mlp --vis wandb
--output-dir outputs/"$SCENE_NAME" --experiment-name "$EXP_NAME"
--trainer.steps-per-save 1000
--trainer.steps-per-eval-image 5000 --trainer.steps-per-eval-all-images 50000
--trainer.max-num-iterations 250001 --trainer.steps-per-eval-batch 5000
--pipeline.datamanager.train-num-rays-per-batch 2048
--pipeline.datamanager.eval-num-rays-per-batch 512
--pipeline.model.sdf-field.inside-outside False
--pipeline.model.background-model mlp \ --pipeline.model.near-plane 0.001 --pipeline.model.far-plane 6.0
--machine.num-gpus 1
--pipeline.model.mono-normal-loss-mult 0.1
panoptic-data
--data "$DATA_PATH"
--panoptic_data False --mono_normal_data True --panoptic_segment False
--orientation-method none --center-poses False --auto-scale-poses False`

![image](https://github.com/user-attachments/assets/9c60e070-c4ea-4680-abcd-f0e2955e14cc)
( Left (GT image), Right (ours) at 280K result )

The training resulted in novel views with a PSNR of  about 22 (like above), and during extraction, the mesh was not reproduced with the same quality. Could you please share the BakedSDF training script?

Thank you.

**Comment by haoyuhsu** [comment]
Hi,

Yes, I agree that BakedSDF may require additional parameter tuning to achieve optimal quality. Could you please try the parameter settings listed below?
```bash
ns-train bakedsdf-mlp --vis wandb \
    --output-dir outputs/"$SCENE_NAME" --experiment-name "$EXP_NAME" \
    --trainer.steps-per-save 1000 \
    --trainer.steps-per-eval-image 5000 --trainer.steps-per-eval-all-images 50000 \
    --trainer.max-num-iterations 250001 --trainer.steps-per-eval-batch 5000 \
    --pipeline.datamanager.train-num-rays-per-batch 2048 \
    --pipeline.datamanager.eval-num-rays-per-batch 512 \
    --pipeline.model.sdf-field.inside-outside True \
    --pipeline.model.scene-contraction-norm l2 \
    --pipeline.model.sdf-field.bias 1.5 \
    --pipeline.model.background-model none \
    --machine.num-gpus 1 \
    --pipeline.model.mono-normal-loss-mult 0.1 \
    panoptic-data \
    --data "$DATA_PATH" \
    --panoptic_data False --mono_normal_data True --panoptic_segment False \
    --orientation-method none --center-poses False --auto-scale-poses False
```

**Comment by seongyeong2** [comment]
Thank you for your prompt reply. @haoyuhsu 

Below are the results based on the parameters you provided. This is the training results after 125K iterations, but the training doesn't seem to be progressing properly.. Could you please check again?


![image](https://github.com/user-attachments/assets/02ca7a29-35ba-46e8-8022-cbf61d118003)

**Comment by haoyuhsu** [comment]
Hi @seongyeong2 

Thank you for bringing this up. I am currently evaluating parameters by re-training the BakedSDF model and I will get back to you once I have finished.

**Comment by haoyuhsu** [comment]
Hi @seongyeong2 

Could you please display your reconstructed surfaces using the default script? This would provide me with a reference regarding the quality. Thank you!

**Comment by haoyuhsu** [comment]
Anyway, this is the bakedsdf-mlp training result from my side:

![image](https://github.com/user-attachments/assets/39c172b2-f49e-45ee-aa67-9dbc87895495)

![image](https://github.com/user-attachments/assets/8cee1f71-6aa4-4870-a7fd-50e46dba806c)

And I used this script for training:
```bash
python scripts/train.py bakedsdf-mlp --vis wandb \
    --output-dir outputs/$scene --experiment-name tmp_test_$scene \
    --trainer.steps-per-save 1000 \
    --trainer.steps-per-eval-image 5000 --trainer.steps-per-eval-all-images 50000 \
    --trainer.max-num-iterations 250001 --trainer.steps-per-eval-batch 5000 \
    --pipeline.datamanager.train-num-rays-per-batch 2048 \
    --pipeline.datamanager.eval-num-rays-per-batch 512 \
    --pipeline.model.sdf-field.inside-outside True \
    --pipeline.model.num-neus-samples-per-ray 24 \
    --pipeline.model.scene-contraction-norm l2 \
    --pipeline.model.sdf-field.bias 1.5 \
    --pipeline.model.background-model none \
    --machine.num-gpus 1 \
    --pipeline.model.mono-normal-loss-mult 0.1 \
    panoptic-data \
    --data ../autovfx/datasets/$scene \
    --panoptic_data False --mono_normal_data True --panoptic_segment False \
    --orientation-method none --center-poses False --auto-scale-poses False
```
The only difference between the updated script mentioned above and this version is the setting for the number of samples per ray: `--pipeline.model.num-neus-samples-per-ray 24`. This adjustment may help stabilize the training process. Additionally, you could consider replacing `bakedsdf-mlp` with `bakedsdf` to achieve faster reconstruction, although this may result in a slight decrease in quality.

**Comment by seongyeong2** [comment]
@haoyuhsu  
Hello! Thank you for your kind response.

I tried training using the script you shared above. However, the eval loss in my results is significantly high. Even though I trained with the same script, why could this be happening? Is there something I might have missed?

![image](https://github.com/user-attachments/assets/5fe29bc2-4fdb-47a0-943a-d6698d66bcdf)
![image](https://github.com/user-attachments/assets/cffa9d10-3320-4324-9a95-251830fc6283)
![image](https://github.com/user-attachments/assets/5ff38110-8dc6-45cf-9ded-b009205ed771)
(  the file with "root / wandb-metadata.json" in wandb runs project's Files )

**Comment by haoyuhsu** [comment]
I would like to make sure:
(1) Did you use our forked implementation of SDFStudio? (https://github.com/zhihao-lin/sdfstudio)
(2) Did you use our data-processing pipeline or directly use the provided data from Google Drive?

If you are using the data preprocessing pipeline (i.e., `colmap_runner.py`), I have added additional code to ensure the exported `transforms.json` can be directly used by SDFStudio. Please kindly pull the latest version.

My current guess is your current camera pose is in the wrong format (OpenCV instead of OpenGL), so SDFStudio can not converge.
